name: Build and Deploy Docker Image to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Update Web App to use Docker Hub image
      - name: Deploy to Azure Web App for Containers
        run: |
          az webapp config container set \
            --name ml \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --container-image-name ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest \
            --container-registry-url https://index.docker.io/v1/ \
            --container-registry-user ${{ secrets.DOCKER_USERNAME }} \
            --container-registry-password ${{ secrets.DOCKER_PASSWORD }}

